### ISSUE TITLE
test

### ISSUE THREAD

**Issue by g4s8** [g4s8/mime#13]
Github webhooks testing

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #13 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnUnassign.react(RbOnUnassign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback....
```

**Comment by 0crat** [comment]
Job `gh:g4s8/mime#13` is in scope.

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #13 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnUnassign.react(RbOnUnassign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback....
```

**Comment by 0crat** [comment]
Job `gh:g4s8/mime#13` assigned to @0crat, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @0crat is not a member of this project yet, but can request to join. @0crat check your [Zerocracy profile](http://www.0crat.com/u/0crat) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @g4s8, total is [+2270](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/mime#13` is already in scope

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #13 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnUnassign.react(RbOnUnassign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback....
```

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/mime/issues/13#issuecomment-337020401))

@g4s8 Oops! Job `gh:g4s8/mime#13` is already in scope.

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/mime/issues/13#issuecomment-337020969))

@g4s8 Job `gh:g4s8/mime#13` is now out of scope.

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/mime/issues/13#issuecomment-337021281))

@g4s8 Job `gh:g4s8/mime#13` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @g4s8, total is [+2335](http://www.0crat.com/u/g4s8).

**Comment by g4s8** [comment]
@0crat assign

**Comment by 0crat** [comment]
> @0crat assign ([here](https://github.com/g4s8/mime/issues/13#issuecomment-337022698))

@g4s8 Option `<login>` is missing in `assign <login>`:
  * `<login>`: "me" or GitHub login of the person to assign

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/mime/issues/13#issuecomment-337034952))

@g4s8 Job `gh:g4s8/mime#13` is now out of scope.

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/g4s8/mime/issues/13#issuecomment-338410396))

@g4s8 Oops! Job `gh:g4s8/mime#13` is not assigned to anyone.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/g4s8/mime/issues/13#issuecomment-338410542))

@g4s8 Job `gh:g4s8/mime#13` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @g4s8, total is [+2450](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @g4s8, total is [+2450](http://www.0crat.com/u/g4s8).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/g4s8/mime/issues/13#issuecomment-338410617))

@g4s8 @g4s8 resigned from `gh:g4s8/mime#13`, please stop working.
