### ISSUE TITLE
Hamcrest matcher for params

### ISSUE THREAD

**Issue by g4s8** [g4s8/mime#8]
Let's introduce new [hamcrest](http://hamcrest.org/JavaHamcrest) matcher for media-type parameters: `HmMimeParam`.
It should have two constructors:
1. primary - with param's name and value's matcher 
```java
new HmMimeParam("encoding", Matchers.equalTo("utf-8"))
```
2. another with param's value as second argument:
```java
new HmMimeParam("encoding", "utf-8")
```

Here is an example of type matcher: https://github.com/g4s8/mime/blob/master/src/main/java/com/g4s8/mime/test/HmMimeHasType.java

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:163)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by Viciouss** [comment]
Working on it.

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/mime#8` was not in scope

**Comment by g4s8** [comment]
@Viciouss thanks!

**Comment by g4s8** [comment]
@rultor release, tag=`1.0`
